### ISSUE TITLE
restrict choosing "Open Source" & "Pre-Production"

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-dash-ui-plan-chooser#1]
Similar to the way we restrict users from choosing the "Pet Project" plan when they're using features it doesn't allow, we also need to restrict them from choosing "Open Source" & "Pre-Production". It should probably also include the "Add 24hrs to Trial" option.

Current Step 2 restriction:
![screen shot 2017-04-24 at 3 30 01 pm](https://cloud.githubusercontent.com/assets/313947/25359673/4e8b8b8a-2903-11e7-8b4d-84616498a99b.png)

We need the same kind of restriction on Step 1:
![screen shot 2017-04-24 at 3 32 42 pm](https://cloud.githubusercontent.com/assets/313947/25359695/5fb87bd4-2903-11e7-972b-af620493608d.png)

**Comment by Tolmark12** [comment]
Changed pricing structure, no longer relevant
